name: Auto-update README

on:
  schedule:
    # Runs every Monday at 1AM UTC. Change this for a different schedule!
    - cron: '0 1 * * MON'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install requests dependency
        run: pip install requests
      - name: Run README generator
        run: python generate_full_readme.py
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update of README.md [skip ci]"
          file_pattern: README.md